[package]
name = "async-zmq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.9.0"
async-trait = "0.1.51"
bytes = "1.0.1"
futures = "0.3.16"
zmq = "0.9.2"


[dev-dependencies]
zmq = "0.9.2"
